title: Ritesh Penumatsa
# logo: <img width="343" alt="Screenshot 2024-08-05 at 12 39 02 AM" src="https://github.com/user-attachments/assets/dd5d9ec3-bce5-419d-a575-248c6b4365bf">
show_downloads: True
theme: jekyll-theme-minimal
